# Generated by Django 5.0.4 on 2025-03-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asiatouragency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='number_of_nights',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.IntegerField(default=None),
        ),
    ]
